version: "3"
services:
  node-app:
    build: ./postApp
    # ports:
    #   - "3000:3000"
    environment:
      - PORT=3000
    depends_on:
      - mongo
  nginx:
    image: nginx:stable-alpine
    ports:
      - 3000:80
    volumes:
      - ./nginx/default.conf/:/etc/nginx/conf/d/default.conf:ro
  mongo:
    image: mongo
    ports:
      - 27018:27017
    environment:
      - MONGO_INITDB_ROOT_USERNAME=dbadmin
      - MONGO_INITDB_ROOT_PASSWORD=Password1
    volumes:
      - mongo-db:/data/db
  redis:
    image: redis
    ports:
      - 6380:6379
volumes:
  mongo-db: