version: "3"
services:
  node-app:
    build:
      context: .
      args:
        NODE_ENV: production
    environment:
      - NODE_ENV=production
      - PORT=3000
    command: npm run build
    command: npm run prod

     