version: "3"
services:
  node-app:
    build:
      context: ./postApp
      args:
        NODE_ENV: production
    environment:
      - NODE_ENV=production
      - PORT=3000
      - MONGO_IP=mongo
      - MONGO_PORT=27017
      - MONGO_USER=dbadmin
      - MONGO_PASSWORD=Password1
    command: npm run prod
  nginx:
    ports:
      - 80:80