version: "3"
services:
  node-app:
    build:
      context: .
      args:
        NODE_ENV: development
    volumes:
      - ./:/app:ro
      - /app/node_modules
    environment:
      - NODE_ENV=development
      - MONGO_IP=mongo
      - MONGO_PORT=27017
      - MONGO_USER=dbadmin
      - MONGO_PASSWORD=Password1
    command: npm run dev
  mongo:
    environment:
      - MONGO_INITDB_ROOT_USERNAME=dbadmin
      - MONGO_INITDB_ROOT_PASSWORD=Password1
    # env_file:
    #   - ./.env
     